### ISSUE TITLE
attaching persistent volumes to templates is immposible

### ISSUE THREAD

**Issue by hananmoiseyev** [tinyzimmer/kvdi#18]
Whenever I am trying to attach a PVC to the Desktop template, I get an error like: json: cannot unmarshal object into Go struct field DesktopConfig.spec.config.capabilities of type []v1.Capabilit

I might have a bad YAML but I have no examples in the docs for reference.

The YAML I am trying to setup is: 

apiVersion: kvdi.io/v1alpha1
kind: DesktopTemplate
metadata:
  name: ubuntu-xfce
spec:
  config:
    allowFileTransfer: true
    allowRoot: true
    init: systemd
    capabilities:
      PersistentVolumeClaim:
        spec:
          accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
          volumeName: volume1
          storageClassName: sc-volume1
          volumeMode: Filesystem
        status:
          phase: Bound
          accessModes:
            - ReadWriteMany
  capacity:
    storage: 1Gi
          
  image: 'ghcr.io/tinyzimmer/kvdi:ubuntu-xfce4-latest'
  imagePullPolicy: IfNotPresent
  resources: {}
  tags:
    applications: minimal
    desktop: xfce4
    os: ubuntu

**Comment by tinyzimmer** [comment]
The current PVC integration relies on a "cluster-level" configuration (`userdataSpec` in the `VDICluster` spec) just for the context of user volumes. There isn't anything in the `DesktopTemplate` API for mounting additional volumes beyond that at the moment.

I can see this making sense specifically in the context of `ReadWriteMany` volumes, e.g. an NFS volume you want mounted to sessions or something. Maybe I'll take a stab at this when I'm going over the other issues.

**Comment by tinyzimmer** [comment]
So in the release I'll do later today I'm going to make it possible to specify additional `volumes`, `volumeMounts` and `volumeDevices` in the `DesktopTemplate`. I _think_ this will satisfy this use case. I'll have the API reference updated with how to use it.

What I am not doing (yet at least) is making it so kvdi will actually **create** PVCs. If you have ReadWriteMany ones that you want to use, you'll have to create them first, and then you can reference them in the `DesktopTemplate`.

**Comment by tinyzimmer** [comment]
The release which will make this a _little_ easier is [here](https://github.com/tinyzimmer/kvdi/releases/tag/v0.1.4).

I'll consider having the controller create PVCs too in a later release, but it would be a larger refactor of the `Desktop` controller that I'm going to save for some other things.

**Comment by hananmoiseyev** [comment]
Thank you for all the work mate, but it seems like it's still not there...
When I am adding the volumeConfig and volumeMounts and volumes, it defaults to an emptyDir. It can't be changed in any way in the UI... I also was succesful to add a PVC but then the VM will not load.

I might be very wrong with my yaml but its quite straight forward:

volumeConfig:
    volumeMounts:
    - mountPath: /path1/path2
      name: vm-path-1
    volumes:
    - emptyDir: {} // <-- THis cannot be deleted...
      name: v-path1
      persistentVolumeClaim:
        claimName: pvc-path-1 //This is a pvc with RWM settings

**Comment by tinyzimmer** [comment]
> When I am adding the volumeConfig and volumeMounts and volumes, it defaults to an emptyDir. It can't be changed in any way in the UI

There is nothing enforcing an `emptyDir` anyway. The only way I can think of this happening is if you are trying to use a volume name that is already used internally. Either way, I can't reproduce what you are describing.

> I also was succesful to add a PVC but then the VM will not load.

I'd check the PVC controller then to see what the issue is. You might also want to look at the pod backing the "Desktop" also, there would be useful information there. Also, these are not VMs. That is probably an important distinction to make.

**Comment by hananmoiseyev** [comment]
> There is nothing enforcing an emptyDir anyway. The only way I can think of this happening is if you are trying to use a volume name that is already used internally. Either way, I can't reproduce what you are describing.
I have created a new template and was able to not have the empty dir. To reproduce, add a template with emptyDir, run the template, disconnect it and then try editing the template...

> I'd check the PVC controller then to see what the issue is. You might also want to look at the pod backing the "Desktop" also, there would be useful information there. Also, these are not VMs. That is probably an important distinction to make.
I was able to mount an NFS volume. This is good enough for now... I will also try to mount a Longhorn volume via PVC to make sure it works.

Thanks again!

**Comment by hananmoiseyev** [comment]
Hi,

I have upgraded to release 0.2.2 and it seems like the volumes patch you added in 0.1.4 stopped working.
When I am trying to add the volumes info to the desktop yaml I get no error but the changes are not saved.

This is what I add:
  volumeConfig:
    volumeMounts:
    - mountPath: /aaa/bbb
      name: aaa1
    - mountPath: /ccc
       name: ccc1
    volumes:
    - name: aaa1
      nfs:
        path: /aaa/bbb
        server: aaaa.bbb.ccc
	- name: ccc1
	  persistentVolumeClaim:
        claimName: pvc-ccc1

**Comment by tinyzimmer** [comment]
That probably means you need to update the CRDs. The latest releast was a big change of the Template CRD. I forgot to add a snippet to the release info about that. Something like this:

```
export KVDI_VERSION=v0.2.2

kubectl apply \
  -f https://raw.githubusercontent.com/tinyzimmer/kvdi/${KVDI_VERSION}/deploy/charts/kvdi/crds/desktops.kvdi.io_templates.yaml
```

**Comment by hananmoiseyev** [comment]
I ran this and still the same issue.
I have also tried a clean install with no difference in result

**Comment by tinyzimmer** [comment]
But the spec has changed a bit also, can you paste the full yaml of your template. Also surround it in fences (`\`\`\) to retain the indentation.

**Comment by tinyzimmer** [comment]
Here is the reference updated with the new spec: https://github.com/tinyzimmer/kvdi/blob/main/doc/desktopsv1.md#template

The `volumes` are declared at the top of the spec, and the mounts and stuff are declared in a new `desktop` block.

**Comment by hananmoiseyev** [comment]
Thanks.

Can you by any chance provide an example for all this? Whatever I try gets me no response from the ui...

**Comment by tinyzimmer** [comment]
The template editor in the UI has bugs of its own and that is a separate story. I'd just look/edit it directly with `kubectl`. It's probably easier that way.

```
kubectl get template [...]
kubectl edit template [...]
```

The benefit of that, is you'll get the actual validation errors which I'm not sure the UI is always floating up properly. 

A simple empty dir example in the new structure would be like this:

```yaml
7 lines (45 sloc)  957 Bytes
  
apiVersion: desktops.kvdi.io/v1
kind: Template
metadata:
  name: ubuntu-xfce
spec:
  volumes:
    - name: test-vol
      emptyDir: {}
  desktop:
    image: ghcr.io/tinyzimmer/kvdi:ubuntu-xfce4-latest
    volumeMounts:
      - name: test-vol
        mountPath: /data
```

**Comment by hananmoiseyev** [comment]
Thank you. It did look like the UI is playing with me here :)>
I was able to deploy bot NFS and PVC via the template.
Keep the great work!

**Comment by tinyzimmer** [comment]
Yea my frontend skills are crap 😛. I'm hoping for a Vue angel to stumble upon the project one day and give the whole UI some much needed love.

**Comment by hananmoiseyev** [comment]
One thing I did see is that the newly added volume is created with permissions to user id 99 which is strange...
