### ISSUE TITLE
[Q] Is it possible to pass custom env to desktop session?

### ISSUE THREAD

**Issue by umberto10** [tinyzimmer/kvdi#19]
Hi, it's me again... Could you tell me, if I can pass bearer token from user oidp login to desktop container as env var? Or how can I simple achieve this?

**Comment by tinyzimmer** [comment]
In my head I'm dissecting this into two parts

- Having information about the user or environment be mappable to additional environment variables in the container
- Keeping information supplied about the user from the OIDC provider in the JWT

The first seems doable, but I'd like to think on it a bit more to mature the idea. That being said, there isn't much information there to begin with about the user or their auth specifically. Everything the API needs to know about a user at any point in time is in the access token that gets generated at login (and later refreshes, but not relevant here). I try to keep it as small as possible and void of sensitive data, so it doesn't contain much info beyond the username and what they are allowed to do. The purpose of this is not having to call out to whatever the authentication provider is for every single request to determine the authorizations.

Which kinda leads to the next part. I throw away the bearer token the OIDP provider gives in favor of one generated internally, after I've extracted the info I need from it. The OIDP is basically just verifying that you exist and have a name and some attributes, then all authorization and token generation for the user is handled by logic in the API. So I guess the question becomes is the token itself something I want to store in the user token (so that it can be used with a potential feature like above). I'll have to think on it. My gut tells me it wouldn't be the safest idea.

**Comment by umberto10** [comment]
I've got your point, but what if I want give to user access to some apps, that require auth and I don't want user to log in again and again? Some k8s apps, like jupyterhub zero, gives optionally `auth_hook` which can be used to provide auth token to pod's container and then use it like env inside. For example you can use it to provide external storage, which k8s cannot handle.

**Comment by tinyzimmer** [comment]
It's a fair point and one that came to mind when I was thinking on it yesterday. What I'm trying to fight out in my head right now is...Is there anything more dangerous that could happen if your access token is compromised AND also has your oauth token inside. 

But what I'm starting to lean towards anyway - is that it should be a user decision. One can maybe opt-in to having that token preserved, knowing the risks that will come with it.

**Comment by umberto10** [comment]
I fully agree with you! Is should be user decision, and I'd love to see this possibility in your app :D

**Comment by tinyzimmer** [comment]
If I do end up seeing this through, it might require a few small refactors in some areas. I'm probably gonna do a release in a little bit that will close the other issues that are open, then I'll investigate this one separately.

**Comment by tinyzimmer** [comment]
Alright. In a little bit there will be images for you to test some things out with. I had to touch a lot of places so I don't want to tag for a bit. The process to test this on your installation will be a little messy.

After [this build](https://github.com/tinyzimmer/kvdi/actions/runs/540963092) is finished you'll want to patch the controller deployment to the latest image.

```bash
kubectl patch deployment kvdi-manager --patch \
    '{"spec":{"template":{"spec":{"containers":[{"name":"kvdi-manager","image":"ghcr.io/tinyzimmer/kvdi:manager-latest"}]}}}}'
```

If you don't have `vdi.spec.app.image` overridden then the manager _should_ replace your app instance with the latest image also. If it doesn't then point that field at "ghcr.io/tinyzimmer/kvdi:app-latest".

You'll then need to update two of the CRDs to the latest version with

```
kubectl apply \
    -f https://raw.githubusercontent.com/tinyzimmer/kvdi/main/deploy/charts/kvdi/crds/kvdi.io_desktoptemplates_crd.yaml \
    -f https://raw.githubusercontent.com/tinyzimmer/kvdi/main/deploy/charts/kvdi/crds/kvdi.io_vdiclusters_crd.yaml
```

Finally, there was a bug in the desktop images that use `systemd` that environment variables set by the controller were not passed through to the user session. There will be new desktop base images (assuming you built from them, if you didn't I can try to help you figure out what you need in your images). So whenever [this build](https://github.com/tinyzimmer/kvdi/actions/runs/540985419) is finished you'll have to rebuild the images for your templates.

---

With all of that though, you'll be able to do a few new things. First the `OIDCConfig` in the `VDICluster` spec has a new field `preserveTokens`. Security disclaimer/info [here](https://github.com/tinyzimmer/kvdi/blob/main/doc/crds.md#OIDCConfig) and example [here](https://github.com/tinyzimmer/kvdi/blob/main/deploy/examples/example-oidc-helm-values.yaml).

Then your `DesktopTemplates` have two new fields. Here is an example leveraging both of them:

```yaml
apiVersion: kvdi.io/v1alpha1
kind: DesktopTemplate
metadata:
  name: ubuntu-xfce
spec:
  image: ghcr.io/tinyzimmer/kvdi:ubuntu-xfce4-latest
  imagePullPolicy: IfNotPresent
  # The same env syntax as regular kubernetes pods
  env:
    - name: HELLO
      value: WORLD
  # Pass data about the user session as environment variables
  envTemplates:
    OIDC_TOKEN: "{{ .Session.Data.access_token }}"
  # Existing functionality...
  config:
    allowFileTransfer: true
    allowRoot: true
    init: systemd
  tags:
    os: ubuntu
    desktop: xfce4
    applications: minimal
```

With all of that, you get something like this

![env](https://user-images.githubusercontent.com/38474291/107062542-13f49d00-67e2-11eb-9bd7-5671d87cfc7b.png)

Let me know how it works out for you if you get a chance to test.

**Comment by tinyzimmer** [comment]
`latest` is probably not good to test anymore because I'm in the middle of finishing a big update to a v0.2.0 tag. The APIs are going to be moved around a bit and all brought up to v1 so the code that is on `main` now will not work with older versions.

You'll be able to tinker with this whenever I finish the release.

**Comment by umberto10** [comment]
That's great! I'll wait until you finish your update. Thanks a lot! I've got another question. Do you think it is possible to run windows in container with kvdi? I was thinking about it for a bit, but the only thing I came up with was a container with vnc client and vm with win10 on it. What do you think about it?

**Comment by tinyzimmer** [comment]
Actually I ended up [releasing](https://github.com/tinyzimmer/kvdi/releases/tag/v0.2.0) it already. There will be another minor one later tonight probably with some small UI fixes mainly. But yea, to get up to it `v0.2` you'll need a clean install as mentioned.

Regarding windows there are two things to consider. The first like you mentioned is it would pretty much have to run in a VM. Which is support I wanted to add anyway for other reasons. Being able to do desktops in containers **or** VMs (even just for Linux) could be pretty cool. That being said it will be a while before I accomplish this.

The second thing to consider is licensing. Mainly making sure that Microsoft wouldn't come after me for making it possible, and you the user wouldn't get in trouble for doing it (or at least have ways to not get in trouble).

**Comment by umberto10** [comment]
Are you sure, it is working after update? I cannot deploy it, even with default config, managerpod has crashLoopBackOff state, no and there's no logs in manager container :c kubectl says it's oomkilled but there is no problem with other applications which consume more resources. There wasn't any problem before v0.2 patch :v

**Comment by tinyzimmer** [comment]
oomkilled sounds weird. I can't reproduce this sadly. The manager pod is **very** lightweight.

You are doing a clean install right?

**Comment by umberto10** [comment]
yup, I delete all with helm, and delete helm, cache. I'm trying to install it with default config, only using [this](https://github.com/tinyzimmer/kvdi#helm).

**Comment by tinyzimmer** [comment]
Version of kubernetes? You removed old CRDs first? 

I dunno, without much detail there isn't much for me to go on since I can't reproduce (on 1.16-1.20) for whatever thats worth.

**Comment by umberto10** [comment]
It's kubernetes 1.20.2. I patched crd's like you said in Upgrading section, but there is no file under this link 
https://raw.githubusercontent.com/tinyzimmer/kvdi/v0.2.0/deploy/charts/kvdi/crds/desktops.kvdi.io_sessions_crd.yaml

**Comment by tinyzimmer** [comment]
The two versions are not going to be able to run side by side for sure. Or well maybe they could but that would cause weird behavior. It also looks like you might be using desktop images from before the release which are also not supported with the new version.

Regarding the OOM I think it might be related to #20 and I suggest we move the discussion there.

**Comment by tinyzimmer** [comment]
^ See that thread - it's an easy fix in your `helm` arguments, but I'm going to fix the chart itself later.

**Comment by tinyzimmer** [comment]
The chart is fixed now 😄

**Comment by umberto10** [comment]
ok, it's working for now! Thanks a lot! :D But with version v0.2.1 <no value> appears in env OIDC_TOKEN :c

**Comment by tinyzimmer** [comment]
I mean if you used my example yaml, that's what its set to.

```yaml
  envTemplates:
    OIDC_TOKEN: "{{ .Session.Data.access_token }}"
```

Change `OIDC_TOKEN` to whatever you want the name of the variable to actually be.

**Comment by umberto10** [comment]
Sorry, it was my bad. It's working perfectly!
