### ISSUE TITLE
Helm deployment on AKS failed with OOMKilled

### ISSUE THREAD

**Issue by immae1** [tinyzimmer/kvdi#20]
Hi i want to install your project on an aks cluster. But the manager pod fails with CrashLoopBackOff OOMKilled.

logs:

> kube-rbac-proxy I0212 09:18:32.850504   1 main.go:186] Valid token audiences: 
>  kube-rbac-proxy I0212 09:18:32.850592       1 main.go:232] Generating self signed cert as no cert is provided
>  kube-rbac-proxy I0212 09:18:33.365315       1 main.go:281] Starting TCP socket on 0.0.0.0:8443
>  kube-rbac-proxy I0212 09:18:33.366432       1 main.go:288] Listening securely on 0.0.0.0:8443 
>  manager stream closed 

kubectl describe pod:

> Name:         kvdi-manager-58ff97d849-7xtk2
> Namespace:    default
> Priority:     0
> Node:         aks-agentpool-12592036-2/10.240.0.4
> Start Time:   Fri, 12 Feb 2021 10:18:28 +0100
> Labels:       app.kubernetes.io/instance=kvdi
>               app.kubernetes.io/managed-by=Helm
>               app.kubernetes.io/name=kvdi
>               app.kubernetes.io/version=v0.2.1
>               helm.sh/chart=kvdi-v0.2.1
>               pod-template-hash=58ff97d849
> Annotations:  <none>
> Status:       Running
> IP:           10.244.1.2
> IPs:
>   IP:           10.244.1.2
> Controlled By:  ReplicaSet/kvdi-manager-58ff97d849
> Containers:
>   kube-rbac-proxy:
>     Container ID:  docker://62d2f50fad42802dfe423bae5c4a251d0191b6fa24ec24678a30237eed24848c
>     Image:         gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
>     Image ID:      docker-pullable://gcr.io/kubebuilder/kube-rbac-proxy@sha256:e10d1d982dd653db74ca87a1d1ad017bc5ef1aeb651bdea089debf16485b080b
>     Port:          8443/TCP
>     Host Port:     0/TCP
>     Args:
>       --secure-listen-address=0.0.0.0:8443
>       --upstream=http://127.0.0.1:8080/
>       --logtostderr=true
>       --v=10
>     State:          Running
>       Started:      Fri, 12 Feb 2021 10:18:32 +0100
>     Ready:          True
>     Restart Count:  0
>     Environment:    <none>
>     Mounts:
>       /var/run/secrets/kubernetes.io/serviceaccount from kvdi-token-66vnx (ro)
>   manager:
>     Container ID:  docker://ce6a9d24fda5687c56793b60f6cb0ad6c7bdbcbd779470ecb9e121dd01549e77
>     Image:         ghcr.io/tinyzimmer/kvdi:manager-v0.2.1
>     Image ID:      docker-pullable://ghcr.io/tinyzimmer/kvdi@sha256:642cfe9c46935201ea40d766684ca9fbb5ffebf03351d10bcfc7f80879f11e67
>     Port:          <none>
>     Host Port:     <none>
>     Command:
>       /manager
>     Args:
>       --health-probe-bind-address=:8081
>       --metrics-bind-address=127.0.0.1:8080
>       --leader-elect
>     State:          Waiting
>       Reason:       CrashLoopBackOff
>     Last State:     Terminated
>       Reason:       OOMKilled
>       Exit Code:    137
>       Started:      Fri, 12 Feb 2021 10:24:42 +0100
>       Finished:     Fri, 12 Feb 2021 10:24:44 +0100
>     Ready:          False
>     Restart Count:  6
>     Limits:
>       cpu:     100m
>       memory:  30Mi
>     Requests:
>       cpu:      100m
>       memory:   20Mi
>     Liveness:   http-get http://:8081/healthz delay=15s timeout=1s period=20s #success=1 #failure=3
>     Readiness:  http-get http://:8081/readyz delay=5s timeout=1s period=10s #success=1 #failure=3
>     Environment:
>       OPERATOR_NAMESPACE:  default (v1:metadata.namespace)
>       POD_NAME:            kvdi-manager-58ff97d849-7xtk2 (v1:metadata.name)
>       POD_NAMESPACE:       default (v1:metadata.namespace)
>       OPERATOR_NAME:       kvdi
>     Mounts:
>       /var/run/secrets/kubernetes.io/serviceaccount from kvdi-token-66vnx (ro)
> Conditions:
>   Type              Status
>   Initialized       True
>   Ready             False
>   ContainersReady   False
>   PodScheduled      True
> Volumes:
>   kvdi-token-66vnx:
>     Type:        Secret (a volume populated by a Secret)
>     SecretName:  kvdi-token-66vnx
>     Optional:    false
> QoS Class:       Burstable
> Node-Selectors:  <none>
> Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
>                  node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
> Events:
>   Type     Reason     Age                    From               Message
>   ----     ------     ----                   ----               -------
>   Normal   Scheduled  6m30s                  default-scheduler  Successfully assigned default/kvdi-manager-58ff97d849-7xtk2 to aks-agentpool-XXXXXX-2
>   Normal   Pulling    6m29s                  kubelet            Pulling image "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0"
>   Normal   Pulled     6m27s                  kubelet            Successfully pulled image "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0"
>   Normal   Created    6m26s                  kubelet            Created container kube-rbac-proxy
>   Normal   Started    6m26s                  kubelet            Started container kube-rbac-proxy
>   Normal   Pulling    6m26s                  kubelet            Pulling image "ghcr.io/tinyzimmer/kvdi:manager-v0.2.1"
>   Normal   Pulled     6m24s                  kubelet            Successfully pulled image "ghcr.io/tinyzimmer/kvdi:manager-v0.2.1"
>   Normal   Created    5m26s (x4 over 6m24s)  kubelet            Created container manager
>   Normal   Started    5m26s (x4 over 6m23s)  kubelet            Started container manager
>   Normal   Pulled     5m26s (x3 over 6m21s)  kubelet            Container image "ghcr.io/tinyzimmer/kvdi:manager-v0.2.1" already present on machine
>   Warning  BackOff    79s (x25 over 6m18s)   kubelet            Back-off restarting failed container`

Do i miss something ? Do you need further informations? 
Thanks in advance !

**Comment by tinyzimmer** [comment]
Hrm. This seems related to the tail end of the discussion in #19. And does give me some more context to work with. I don't have a cloud cluster available but I haven't been able to replicate on my machine.

The kube-rbac-proxy is something new from the kubebuilder-v3 migration I just did, and those are the logs you showed. Coud you potentially paste the logs from the manager container instead `kubectl logs -c manager ...`?

**Comment by tinyzimmer** [comment]
Oh! Ha!

It's in the helm chart. There is an easy fix, but I should probably fix the chart instead I just can't get to it right now. Before I had the resource restraints undefined, but `kubebuilder` puts these there by default so I figured what the hell:

```
Limits:
cpu: 100m
memory: 30Mi
Requests:
cpu: 100m
memory: 20Mi
Limits:
cpu: 100m
memory: 30Mi
Requests:
cpu: 100m
memory: 20Mi
```

It would seem 30Mi is probably definitely not enough for the workload the manager has on its plate. You can override this with a `values.yaml` or set (e.g. `--set manager.resources={}`)

**Comment by immae1** [comment]
after some investigations i found out that your pod limits are to restrictive! 30mi memory ...

**Comment by tinyzimmer** [comment]
jinx

**Comment by tinyzimmer** [comment]
I'll set the defaults in the helm chart back to just `{}` in a little bit, but for now just change the values to fit your needs.

I'll keep the issue open so I remember to take care of this later.

**Comment by tinyzimmer** [comment]
The thing is 30Mi is probably not even that bad for most of the time and that's why I couldn't reproduce. But the initial workload it has on its plate at first install involves a lot of crypto so that could definitely produce different results in different environments.

**Comment by tinyzimmer** [comment]
Charts should now be fixed
