### ISSUE TITLE
invalid example image name

### ISSUE THREAD

**Issue by umberto10** [tinyzimmer/kvdi#22]
I copied example of ubuntu image, and pasted it in web gui. After creation it's saying `emplate.desktops.kvdi.io "ubuntu-xfce" is invalid: spec.image: Required value`. I don't know what to do :v

**Comment by tinyzimmer** [comment]
If you took the example directly from Github on main then its only compatible with whatever I have at the HEAD of that branch right now...

Either way, `spec.image` suggestsyou are running older versions and trying to use new syntax.

Also, as in the other thread, that part of the UI is very unstable and I'd verify these issues directly with `kubectl` first, you'll get better errors.

**Comment by umberto10** [comment]
em, helm is telling me I'm using v0.2.2, and `kubectl` says I have missing fields as UI

**Comment by tinyzimmer** [comment]
But there is no `spec.image` in the templates in v0.2.2. Which makes me think you maybe need to update the CRDs (which helm doesn't do). 

There is a blurb about it in the release. https://github.com/tinyzimmer/kvdi/releases/tag/v0.2.2

**Comment by umberto10** [comment]
Ok, now I'm able to do it, but another thing is that, screen in blinking and it's showing `Connecting to: ...` and then hourglass and keeps changing it forever. This appears only with ubuntu image, dosbos is working correctly

**Comment by tinyzimmer** [comment]
That happens to me **super** rarely, and I usually just have to refresh.

But looking at the browser console logs and logs for the proxy container on that desktop pod might have insight also.

If anything, I think I might draw up some ISSUE templates with guidance on how to collect good debugging information.

**Comment by umberto10** [comment]
This is from proxy:
```2021-02-23T07:40:16.352Z        INFO    kvdi_proxy      Received display proxy request, connecting to unix:///var/run/kvdi/display.sock
2021-02-23T07:40:16.352Z        ERROR   kvdi_proxy      Failed to connect to display server     {"error": "dial unix /var/run/kvdi/display.sock: connect: no such file or directory"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
main.websockifyHandler
        /build/cmd/kvdi-proxy/handlers.go:90
golang.org/x/net/websocket.Server.serveWebSocket
        /go/pkg/mod/golang.org/x/net@v0.0.0-20201110031124-69a78807bb2b/websocket/server.go:89
golang.org/x/net/websocket.Server.ServeHTTP
        /go/pkg/mod/golang.org/x/net@v0.0.0-20201110031124-69a78807bb2b/websocket/server.go:70
github.com/gorilla/mux.(*Router).ServeHTTP
        /go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210
github.com/gorilla/handlers.loggingHandler.ServeHTTP
        /go/pkg/mod/github.com/gorilla/handlers@v1.5.1/logging.go:47
net/http.serverHandler.ServeHTTP
        /usr/local/go/src/net/http/server.go:2843
net/http.(*conn).serve
        /usr/local/go/src/net/http/server.go:1925
{"time":"2021-02-23T07:40:16.352509814Z","method":"GET","path":"/api/desktops/ws/k8s-kvdi/ubuntu-xfce-7dxtx/display","statusCode":200,"size":0,"remoteHost":"10.244.180.17"}
```
Browser cosole logs:
![image](https://user-images.githubusercontent.com/43953088/108824983-b5d9ff00-75c2-11eb-9c2d-62b9cd0d1931.png)

![image](https://user-images.githubusercontent.com/43953088/108824923-9d69e480-75c2-11eb-9bb2-06ece1b31422.png)

**Comment by tinyzimmer** [comment]
The proxy is informative enough in this case. The VNC server is failing to start. Debugging this can be a pain, but while the UI is flickering trying to connect, you _could_ exec into the pod a la

```
kubectl exec -it <desktop_name> -c desktop -- bash
```

And then start poking around. It's all systemd in there, and the VNC server is called `display.service`. So you _should_ be able to do things like `journalctl -u display` to see its logs.

Beyond that though, this is a weird issue to occur and the only thing that would make sense is version skew. There were changes to the `init` script in the desktop images in this repo recently, but the latest ones _should_ be fine for the latest version. The only skew I could see is if your server has old ones cached. You could force them to pull new ones by setting `desktop.imagePullPolicy` to `Always` briefly in the template.

**Comment by tinyzimmer** [comment]
Actually I'm able to reproduce this, it does seem like there is skew with the latest published desktop images, I'm wondering if I just need to push a new one.

**Comment by tinyzimmer** [comment]
I'll push a new latest desktop image that addresses this later. It's due to a change in the environment variable that sets the VNC socket. It used to be called `VNC_SOCK_ADDR` but I changed it on master to `DISPLAY_SOCK_ADDR` because I am working on adding SPICE support. I don't version control the desktop images, latest is always just whatever master looks like, which may become an issue later on I'm realizing.

I'll let you know when it's there to pull.

**Comment by tinyzimmer** [comment]
[This build](https://github.com/tinyzimmer/kvdi/runs/1960615891?check_suite_focus=true) should produce working desktop images on latest.

**Comment by tinyzimmer** [comment]
I am noticing some other smaller issues inside those desktop images around directory permissions. I'll try to round them up in the next release I do.

**Comment by umberto10** [comment]
Ok, thanks! it's working with latest version
